### ISSUE TITLE
Access to material and demo

### ISSUE THREAD

**Issue by rajurh** [microsoft/ignite-learning-paths-training-afun#29]
Is there a way to get access to demo and materials like PPT for the same.

e.g. https://github.com/microsoft/ignite-learning-paths-training-afun/tree/master/afun60
We are not able to download slides etc

**Comment by fboucher** [comment]
@rajurh you are right. We will fix that soon. In the meantime, if you need the slides you can find them here: https://github.com/microsoft/ignite-learning-paths-training-afun/blob/master/afun60/presentations.md

**Comment by fboucher** [comment]
Thank you @rajurh for your help to find this issue. The document has been updated, I will now close this issue. 👍

**Comment by rajurh** [comment]
> Thank you @rajurh for your help to find this issue. The document has been updated, I will now close this issue. 👍

Thanks for addressing the issue and fixing it
