### ISSUE TITLE
Powerpoint link not available

### ISSUE THREAD

**Issue by lbonnet34** [microsoft/ignite-learning-paths-training-afun#30]
On https://github.com/microsoft/ignite-learning-paths-training-afun/tree/master/afun60 the powerpoint link is not available, it's redirecting to https://microsoft.sharepoint.com/:p:/t/CloudDevAdvocacy/EY-NxkmfzDpHpJm3d-CngPgBI4dIa9Y57hgkG02Kek95rQ?e=XaDlg0 and it's not available.

Could you please fix it ? TY

**Comment by fboucher** [comment]
Thanks @ignitetourlb we will fix this. In the meantime if you need the slides you can find them here: https://github.com/microsoft/ignite-learning-paths-training-afun/blob/master/afun60/presentations.md

**Comment by fboucher** [comment]
@ignitetourlb the document has been updated, I will now close this issue. Thank you a lot for your help in finding this issue.👍
