### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by scottcate** [microsoft/ignite-learning-paths-training-afun#36]
https://github.com/microsoft/ignite-learning-paths-training-afun/tree/master/afun60/demos#demo-1---aci-time-permittting

Has broken links in the table 
![image](https://user-images.githubusercontent.com/617586/70750885-0e024980-1d0e-11ea-8774-d85fa78289e7.png)
Are all broken links.

Also,
https://github.com/microsoft/ignite-learning-paths-training-afun/tree/master/afun60
![image](https://user-images.githubusercontent.com/617586/70751039-5a4d8980-1d0e-11ea-8590-1c32cf5aa899.png)
Doesn't provide a video link.

![image](https://user-images.githubusercontent.com/617586/70751067-689ba580-1d0e-11ea-8e39-4df3380f813e.png)
can be updated with more current information. It's missing Demo Instructions, can these please be added?

**Comment by fboucher** [comment]
@spboyer links are still broken for the section **Deployment**
There is no deployment instructions

**Comment by spboyer** [comment]
#42 #43 #44 #45 - Should address outstanding issues.
