### ISSUE TITLE
confusing sentence in the README

### ISSUE THREAD

**Issue by videlalvaro** [microsoft/ignite-learning-paths-training-afun#56]
>But when you boil it down, what you want to do, is you want to specify the properties of things that you've got running those properties might be that it made might need to be named in a certain way that certain people might need to have access to it but that's a way of thinking about governance.

I have trouble understanding that sentence from the **afun80** README, specifically with all the _might be_ and _might need_.

**Comment by fboucher** [comment]
It's not fixed, so I will close this issue. Thank you @videlalvaro for your feedback it's really appreciated.
