### ISSUE TITLE
Corrections on slide 23 and 24

### ISSUE THREAD

**Issue by cesar-younes** [microsoft/ignite-learning-paths-training-afun#65]
Slide 23
The definition of Azure Table Storage should be structured not unstructured
see: https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-overview#what-is-table-storage

Slide 24
Typo: the definition should say identity instead of identify

**Comment by fboucher** [comment]
Nice catch @cesar-younes I updated the slides. The changes will be visible soon.
